# This Travis-CI file only runs unit tests on the MDTF code.
# It does not make use of external test data and does not test the scientific 
# content of individual diagnostics.

# Config validator: https://config.travis-ci.com/explore 

os: linux
dist: xenial # default
language: shell # synonym for "minimal". Use instead of "python" to save disk space; all software installed through conda
# sudo: false # deprecated in Travis
python: '2.7' # only supported version, for now

branches:
  only:
    - main
    - develop
    - /^feature/ 

before_install: 
  # TRAVIS_BUILD_DIR = abs path to checked-out repo
  - BUILD_PARENT="$( cd "$( dirname "$TRAVIS_BUILD_DIR" )" >/dev/null 2>&1 && pwd )"
  - POD_OUTPUT="${BUILD_PARENT}/wkdir/MDTF_QBOi.EXP1.AMIP.001_1977_1981/EOF_500hPa"
  - echo "$TRAVIS_BUILD_DIR"
  - echo "$BUILD_PARENT"
  - echo "$POD_OUTPUT"
  - cd "$BUILD_PARENT"

install:
# miniconda setup taken from official guide at 
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  # - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # MDTF-specific setup: install all conda envs
  - $TRAVIS_BUILD_DIR/src/conda/conda_env_setup.sh --all --conda_root "$HOME/miniconda"

  - df -h # Log space remaining for data

  # attempt FTP data fetch for EOF_500hPa
  # allow 20 min for transfer before timeout; Travis only allots 50 min for everything
  - curl --verbose --ipv4 --connect-timeout 8 --max-time 1200 --retry 128 --ftp-ssl --disable-epsv --ftp-pasv -u "anonymous:anonymous" ftp://ftp.gfdl.noaa.gov/pub/thomas.jackson/travis_test.tar --output travis_test.tar
  - tar -xvf travis_test.tar
  - mkdir wkdir
  - ls # debug

  - df -h # Log space remaining

before_script:
  - cd "$TRAVIS_BUILD_DIR"

script:
  # trivial check that install script worked
  - ./mdtf --version

  # try running EOF_500hPa
  - ./mdtf -f "${TRAVIS_BUILD_DIR}/tests/travis_test.jsonc"
  - ls wkdir
  - ls "$POD_OUTPUT"
  - ls "${POD_OUTPUT}/obs"
  - ls "${POD_OUTPUT}/model"
  # dump log
  - cat "${POD_OUTPUT}/EOF_500hPa.log"

  # run unit tests
  - conda activate _MDTF_base
  - python -m unittest discover
