# ==================================================================================================
# 7. MJO teleconnection Diagnostic 
#   This requires daily-timescale precipitation rate(mm/day), OLR (w/m2), zonal wind (m/s) at 850 and 250-hPa levels and
#   geopotential height(m) at 250-hPa
#   For further details see comments section of /var_code/MJO_teleconnection/mjo_teleconnection.py
#   Each variable should store in a single file. 
#   The codes are in NCL
# ==================================================================================================

settings:
  driver: mjo_teleconnection.py
  long_name: MJO teleconnection Diagnostic 

# USAGE varlist
# var_name      time-frequency     [requirement]
#
# - var_name: as found in var_code/util/set_variables_*
# - freq: mon (monthly), day, 6hr, 3hr, 1hr
# - requirement = blank  (default = optional)                                          
#                      required (package cannot run without this)                           
#                      required unless field_name field_name2 ...
# - alternates: 
#
#   nb. if a variable is required at multiple time frequencies,
#       list it separately for each one
#
#          Clearly the developer can just leave out optional files
#          However, it is always nice to get an upfront warning of missing files

varlist:
  - var_name: pr_var
    freq: day
    requirement: required
  - var_name: rlut_var
    freq: day
    requirement: required
  - var_name: u850_var
    freq: day
    requirement: required
  - var_name: u250_var
    freq: day
    requirement: required
  - var_name: z250_var
    freq: day
    requirement: required